-- insert meals seed data

INSERT INTO freshplatez.meals
(short_description,price_small,price_large,ingredients,
calories_small,calories_large,lead_time,image_name,reheat_time)
VALUES
('Chicken Ratatouille and Vegan Bechamel', 10.99,12.99, 'ORGANIC SKINLESS CHICKEN BREAST, ZUCCHINI, RED PEPPERS, ROMA TOMATOES, 
SUMMER SQUASH, EGGPLANT, RUTABAGA, HAZELNUTS, NUTRITIONAL YEAST, WATER, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'ChickenOverRatatouilleAndVeganBechamel.jpg','00:30:00'),

('Braised Turkey and Cabbage over Sweet Potato Noodles', 10.99,12.99, 'Ingredients text area',
'300-400','500-600',2, 'FreshPlatezLogo.jpg','00:30:00'),

('Pork and Beef Pho', 10.99,12.99, 'LEAN ORGANIC PORK TENDERLOIN, SWEET POTATO STARCH, SNAOW PEAS, BOK CHOY, BEEF BONES, WATER, CELERY, CARROTS, ONION,
GARLIC LEMON GRASS, CILANTRO, THAI BASIL, VEGTABLE PROTEIN FROM SOYBEAN, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'PorkandBeefPho.jpg','00:30:00'),

('Turkey Havarti over roasted herb potatoes and broccoli', 10.99,12.99, 'Ingredients text area',
'300-400','500-600',2, 'FreshPlatezLogo.jpg','00:30:00'),

('Meatloaf and Cauliflower Mashed Potatoes', 10.99,12.99, 'Ingredients text area',
'300-400','500-600',2, 'FreshPlatezLogo.jpg','00:30:00'),

('Beef Burger over Spinach, Carrots, pickled Zucchini a Sweet Potato Fries', 10.99,12.99, 'Ingredients text area',
'300-400','500-600',2, 'BeefBurgeroverSpinachCarrotspickledZucchiniaSweetPotatoFries.jpg','00:30:00'),

('Chicken Tinga', 10.99,12.99, 'ORGANIC BONELESS SKINELESS CHICKEN THIGHS, GARBANZOS, TOMATO PASTE, CHICKEN BONES, WATER, CARROTS, CELERY,
 ONION, GARLIC, BAY LEAF, SHERRY VINEGAR, EXTRA VIRGIN OLIVE, SALT AND PEPPER','300-400','500-600',2, 'ChickenTinga.jpg','00:30:00'),

('Chicken and Rice Noodle Stir fry', 10.99,12.99, 'Ingredients text area',
'300-400','500-600',2, 'ChickenandRiceNoodleStirfry.jpg','00:30:00'),

('Buffalo Pork Loin & Cauliflower Mashed', 10.99,12.99, 'ORGANIC BONELESS PORK LOIN, CAULIFLOWER, RUSSET POTATOES, YELLOW 
ONION, GARLIC, AGED CAYENNE RED PEPPERS, VINEGAR, PALM FRUIT, CANOLA, SOY BEAN, FLAX, OLIVE OIL, WATER, SALT AND PEPPER','300-400','500-600',2, 'BuffaloPorkLoinAndCauliflowerMashed.jpg','00:30:00'),

('Grilled Pork Chop, Roasted Cauliflower, Basmati Rice and Romesco Sauce', 10.99,12.99, 
'ORGANIC LEAN BONELESS PORK CHOP, ENRICHED WHITE BASMATI RICE, CAULIFLOWER, RED PEPPER, PUMPKIN SEEDS, TOMATO PASTE, WATER, EXTRA VIRGIN OLIVE OIL, SALT, PEPPER AND CHAMPAGNE VINEGAR',
'300-400','500-600',2, 'GrilledPorkChopRoastedCauliflowerBasmatiRiceAndRomescoSauce.jpg','00:30:00'),

('Italian Thanksgiving Dinner', 10.99,12.99, 'TURKEY BREAST TENDERLOIN, CALASPARRA RICE, ONION, ACORN SQUASH, GALA APPLE, WATER, PALM FRUIT,
 CANOLA, SOY BEAN, FLAX, OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'ItalianThanksgivingDinner.jpg','00:30:00'),

('Not Your Grandmas Lasagna', 10.99,12.99, 'ORGANIC 93% LEAN GROUND BEEF, TOMATOES, CARROTS, CELERY, SHALLOTS, CREMINI MUSHROOMS, BUTTERNUT SQUASH,
PARSNIPS, YUKON POTATOES, RUTABAGA, WATER, NUTRITIONAL YEAST, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'NotYourGrandmasLasagna.jpg','00:30:00'),

('Protein Packed Turkey Meatballs Quinoa Pasta And Spinach Marinara', 10.99,12.99, 'ORGANIC 93% LEAN GROUND TURKEY,
WHOLE GRAIN OATS, EGG WHITES, GREEN BELL PEPPER, SHALLOT, SWEET PAPRIKA, DRIED OREGANO, DRIED BASIL, GARLIC, ROASTED PLUM TOMATOES, FROZEN SPINACH, ONION POWDER, ORGANIC CHICKPEA FLOWER, WATER, 
EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'ProteinPackedTurkeyMeatballsQuinoaPastaAndSpinachMarinara.jpg','00:30:00'),

('Pulled Pork And Pineapple Pablano Pepper Salsa Borrito Bowl', 10.99,12.99, 'ORGANIC LEAN BONELES PORK LOIN,
ENRICHED WHITE RICE, ORGANIC SPINACH, WATER, ORGANIC PINEAPPLE, CHARRED PABLANO PEPPER SHALLOT, ORGANIC CHERRY TOMATOES, YELLOW CORN, BLACK BEANS, GINGER POWDER, GARLIC POWER, SWEET PAPRIKA,
EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'PulledPorkAndPineapplePablanoPepperSalsaBorritoBowl.jpg','00:30:00'),

('Sesame Orange Ginger Chicken Over Roasted Veg And Quinoa', 10.99,12.99, 'SKINLESS CHICKEN BREAST, SUMMER SQUASH, ZUCCHINI,
ORGANIC QUINOA, WATER, CHICKEN BONES, FRESH ORANGE JUICE, ORANGE ZEST, GINGER POWDER, GARLIC, SESAME SEED, SESAME OIL, CORN STARCH, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER',
'300-400','500-600',2, 'SesameOrangeGingerChickenOverRoastedVegAndQuinoa.jpg','00:30:00'),

('Shrimp And Chicken Poke Bowl', 10.99,12.99, 'FROZEN SHRIMP, SKINELSS CHICKEN BREAST, CALASPARRA RICE, CARROTS, EDAMAME, PICKLE GINGER,
SHERRY VINEGAR, SCALLIONS, WASABI POWDER, WATER, SESAME SEEDS, VEGETABLE PROTEIN FROM SOYBEAN, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'ShrimpAndChickenPokeBowl.jpg','00:30:00'),

('Taco ‘Bout A Salad', 10.99,12.99, 'ORGANIC 93% LEAN GROUND TURKEY, ZUCCHINI, ENRICHED WHITE RICE, ORGANIC GRAPE CONFETTI TOMATOES,
ORGANIC MANGO, CILANTRO, SHALLOTS, WATER, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'TacoBoutASalad.jpg','00:30:00'),

('Tasty Whip Up Stir Fry', 10.99,12.99, 'ORGANIC SKINLESS CHICKEN, SNOW PEAS, BEAN SPROUTS, POTATO STARCH, CARROTS, CHOY SUM, PEANUTS, CANOLA,
SCALLIONS, SESAME, SOY, GINGER, SALT AND PEPPER','300-400','500-600',2, 'TastyWhipUpStirFry.jpg','00:30:00'),

('Thia Chicken And Vegatable Rice Noodle Stir Fry', 10.99,12.99, 'SKINLESS CHICKEN BREAST, CARROTS, CREMINI MUSHROOMS,
RED BELL PEPPER, BROCCOLI, ZUCCHINI, RICE FLOWER, SESAME, VEGETABLE PROTEIN FROM SOYBEAN, EXTRA VIRGIN OLIVE OIL, LEMON GRASS, THAI CHILI PEPPER, GARLIC, ONION, GINGER, BASIL, CILANTRO,
LIME, SALT AND PEPPER','300-400','500-600',2, 'ThiaChickenAndVegatableRiceNoodleStirFry.jpg','00:30:00'),

('Turkey, Butternut Squach And Kale Rissotto With A Cranberry Gastrique', 10.99,12.99,
'ORGANIC 93% LEAN GROUND TURKEY, BUTTERNUT SQUASH, TUSCAN KALE, CALASPARRA RICE, WATER, CHICKEN BONES, CELERY, CARROTS, ONION, BAYLEAF, FROZEN CRANBERRIES, ORGANIC HONEY, SHERRY VINEGAR,
THYME, EXTRA VIRGIN OLIVE OIL, SALT AND PEPPER','300-400','500-600',2, 'TurkeyButternutSquachAndKaleRissottoWithACranberryGastrique.jpg','00:30:00'),

('Beef Stroganoff Over Sweet Potatoes', 10.99,12.99,
'BEEF CHUCK, TOMATOES, CARROTS, CELERY, SWEET PEPPERS, ONION, SWEET POTATO, OLIVE OIL, ALEPPO PEPPER, SALT AND PEPPER','300-400','500-600',2, 'BeefStroganoffOverSweetPotatoes.jpg','00:30:00');

